function init(self)
	msg.post(".", "acquire_input_focus")
end

function final(self)
	msg.post(".", "release_input_focus")
end

function on_input(self, action_id, action)
	if action.pressed and gui.pick_node(gui.get_node("continue"), action.x, action.y) then
		msg.post("level_select:/controller", "continue")
	end
	if action.pressed and gui.pick_node(gui.get_node("title"), action.x, action.y) then
		msg.post("main:/controller", "title")
	end
end
