local upForce = 0
local rotation = vmath.quat()
local rotation_speed = 0
local updated_position = vmath.vector3(40, 0, 0)

local function level_restart()
	msg.post("level_select:/controller", "restart")
end

function init(self)
	msg.post(".", "acquire_input_focus")
end

function final(self)
	msg.post(".", "release_input_focus")
end

function update(self, dt)
	local pos=go.get_position()
	local rotate = go.get_rotation()
	
	updated_position.y = pos.y + upForce*dt

	if updated_position.y > 720 then
		level_restart()
	end
	if updated_position.y <=0 then
		level_restart()
	end
	
	local new_z_angle=rotate.z + rotation_speed*dt
	
	
	rotation = vmath.quat_rotation_z(new_z_angle)
	
	go.set_position(updated_position)
	go.set_rotation(rotation)
	if upForce > 0 or updated_position.y > 0 then
		upForce = upForce - 10
	end
	if rotation_speed>0 then
		rotation_speed=rotation_speed-2
		if rotation_speed < 0 then
			rotation_speed=0
		end
	end
end


function on_message(self, message_id, message, sender)
	if message_id == hash("contact_point_response") then
		local won = false
		print(message.other_group, message.other_id, message.other_position, message.own_group)
		if message.other_group == hash("wall") then
			level_restart()
		end
		if message.other_group == hash("win") and won == false then
			won = true
			msg.post("level_select:/controller", "next_level")
		end
	end
end

function on_input(self, action_id, action)
	if action_id == hash("player_spin") then
		upForce=upForce+30
		rotation_speed = rotation_speed+5
	end
end
