local speed = -70
function init(self)
	msg.post(".", "acquire_input_focus")
end

function final(self)
	msg.post(".", "release_input_focus")
end

function update(self, dt)
	local pos=go.get_position()
	pos.x = pos.x+speed*dt
	go.set_position(pos)
end 


function on_message(self, message_id, message, sender)
	if message_id == hash("contact_point_response") then
		print("contact")
	end
end

function on_input(self, action_id, action)
end
